### ISSUE TITLE
Html Readme is incomplete

### ISSUE THREAD

**Issue by Flabort** [TheLX5/Powerups#1]
As the title says, Html Readme is incomplete. 

Only one page is view able, that with the most basic instructions of how to get started.

Information on graphics, included powerups (very important), and the FAQ are nonexistant, as are the advanced topics.

**Comment by TheLX5** [comment]
The 3.0.0 beta version is a huge WIP, no powerups are added in that version and some bugs have been fixed already in a upcoming version. I suggest wait patiently until I manage to update this.
You can follow the progress of this project in the Discord Guild: https://discord.gg/zMX6bY8

**Comment by Flabort** [comment]
OK, thanks :) I will wait.

**Comment by TheLX5** [comment]
The readme is mostly finished, it's missing a few advanced docs that I may include in a later update.
