### ISSUE TITLE
Yoshi/1-Up Popping whenever I hit the question block.

### ISSUE THREAD

**Issue by stahpittgetzomehelp** [TheLX5/Powerups#16]
So whenever I hit the question block, Yoshi will pop-up, along with the power-up and after I hit another item, A Green version of said powerup will appear out of a yoshi egg.

**Comment by TheLX5** [comment]
I have no idea how to replicate this.

**Comment by TheLX5** [comment]
Probably got fixed at some point, if not, just open another Issue with proper documentation.
