### ISSUE TITLE
Death after goal

### ISSUE THREAD

**Issue by torzod** [TheLX5/Powerups#58]
**Describe the bug**
By carrying a 32x32 ice block and turning to the left as you collect a goal orb, you get crushed by the ice block even after winning the level.

**To Reproduce**
1. Make a level with a goal orb and ice flower and chuck
2. freeze chuck
3. run to the goal orb from the left, then turn to face left right before hitting the goal.
4. the ice block will be thrown from mario's left side to the right, crushing him

**Expected behavior**
not dying

**Video**
i don't know how to make one

**External resources usage**
I have applied many different patches/blocks/sprites, but have not used any other tools
**Additional context**

**Comment by TheLX5** [comment]
Fixed on https://github.com/TheLX5/Powerups/commit/44ebdeac27d2fae8a215ec86fb3f8c89026d2de3
