### ISSUE TITLE
Flower roulette is missing the cloud flower & boomerang flower

### ISSUE THREAD

**Issue by torzod** [TheLX5/Powerups#59]
**Describe the bug**
With the "Flower Roulette" sprite, the cloud flower never spawns, despite it being a flower as well.

**To Reproduce**
1. Make a level with a flower roulette sprite
2. watch how it cycles
3. fire -> ice -> superball -> bubble -> fire ...
4. the could flower never appears

**Expected behavior**
Given that the item is called "Flower Roulette" i expected all "flower" powerups to be included, but the cloud was not.

**Video**
Try adding GIFs or Videos about the problem so we can understand it better.

**External resources usage**
Try providing information about what tools do you use and what codes have you inserted in your ROM so we can understand your problem.

**Additional context**
The Boomerang flower also does not appear

**Comment by TheLX5** [comment]
These roulettes are premade ones and you can edit its contents by editing the sprite's Extension info. If you hover over the roulette sprite, it will display a description containing a lot of options that you can use to build your own roulette. Try Alt+Right click on a roulette sprite, it should pop out a window with some information on it and try editing the Extension field, each value corresponds to the values that were displayed in the description.

Newer PIXI builds allow more extra bytes on custom sprites, it may be worth looking into it to expand the amount of possible items on a roulette.
