### ISSUE TITLE
Spin Jumps are a bit wonky with Rocket Boots

### ISSUE THREAD

**Issue by MarioFanGamer** [TheLX5/Powerups#60]
I found two issues with Rocket Boots: The "jumped on enemy" flag doesn't get cleared when on ground which results in the next jump being a rocket boost (even a spin jump and if you already have used a boost). Speaking of "jumped on enemy": It also cancles spin jumps.

**Comment by TheLX5** [comment]
Fixed by MarioFanGamer on https://github.com/TheLX5/Powerups/pull/61
