### ISSUE TITLE
Boomerang Flower jankiness

### ISSUE THREAD

**Issue by FedoraFriday** [TheLX5/Powerups#63]
I've run in to some issues with the boomerang flower. I will state what patches I'm using just in case there are some overlaps causing the issues.

- Disable 2-player.
- Nuke statusbar (on the side note, you can still use the item box despite there being no status bar)
- Lunar magic 3.3.0

The issues I've encountered are as follows.
1: I shoot a boomerang, and they can hit a target despite being off-screen far away from the projectile. This makes it so that, whenever an enemy is just barely on screen, as soon as you shoot a boomerang, it just kills the enemy. The issue seems to be somewhat random, sometimes it depends on Y-coordinates whether this bug exists, so if you're below an enemy it won't do anything, and other times it just kills whatever is on screen no matter the Y-coordinate.
Also, sometimes when you're facing away from an enemy that is fully on screen, shoot a boomerang, it will kill said enemy behind you.

2: Pokey enemies, the vanilla versions, can be retrieved like items such as mushrooms, despite the properties asm file stating that it should behave normally, IE can't be killed.
db %00000000			; Sprite 70: Pokey
3: Generators can also be manipulated with the boomerang (What? lol) The side exit generator sprite can be boomerang'd to generate into the fireplace sprite, as you can manipulate the x-value to move it over one place. 

Because the hammer power-up is similar, I suspect similar issues might exist with it, though through some testing I've only seen hammers kill enemies off-screen very occasionally.

**Comment by TheLX5** [comment]
This was a report on a version that hasn't been released. Fixed on https://github.com/TheLX5/Powerups/commit/3e699e10c130430ebdbc809b3e1bb4fdbeea1b98
