### ISSUE TITLE
Shell suit tech / bug?

### ISSUE THREAD

**Issue by FedoraFriday** [TheLX5/Powerups#64]
If you are in the shell suit's shell form, going in one direction (lets say left), then pause the game, hold the opposite direction (right), you will turn right without having to hit a wall, sprite, or exit the suit to manually turn around.

IMHO, don't fix this, it could be an interesting gimmick.

**Comment by TheLX5** [comment]
Fixed on https://github.com/TheLX5/Powerups/commit/52b586ab44d8ef18d2691c6825eab00c49552458
