### ISSUE TITLE
Poison mushroom block is set incorrectly. and Item Roulette/Item spawner does not generate electronic flowers.

### ISSUE THREAD

**Issue by HayashiNeru** [TheLX5/Powerups#66]
Poison mushroom block is set incorrectly.

incorrectled blocks:
object_powerup_blocks/poison_mushroom.asm
instant_question_mark_blocks/poison_mushroom.asm
question_mark_blocks/poison_mushroom.asm

These blocks should generate sprite number 13. But these are sprite number 12.

and, Item Roulette/Item spawner does not generate electronic flowers.

**Comment by TheLX5** [comment]
Fixed at https://github.com/TheLX5/Powerups/commit/5ca931e3bdd709f978c01f9b1ed9855a618cca90 , https://github.com/TheLX5/Powerups/commit/ff768e5721c2281f579106d33a71cafc4609b4e7 and https://github.com/TheLX5/Powerups/commit/ed5739309b755e5dcc7757816896da30b4be319e
