### ISSUE TITLE
LSMW Graphical Glitch

### ISSUE THREAD

**Issue by DrPickens** [TheLX5/Powerups#69]
**Describe the bug**
When running a rom patched with this in LSMW, Mario turns into a messy block of pixels. Everything else is uneffected.
**To Reproduce**
1. Apply the patch
2. Install LSMW
3. Run the rom in LSMW

**Expected behavior**
Mario looks normal

**Picture**
https://i.imgur.com/ve4eRVB.png

**Comment by TheLX5** [comment]
Open lmsw.cfg and set disablefastload to 0. The patch requires to run some code during level transitions, that's why it breaks with the option enabled.

**Comment by DrPickens** [comment]
It was already on 0 so I put it on 1 and this fixed the issue!
