### ISSUE TITLE
Custom Powerups the latest version seems to be glitched the graphics and it was incompatible with many resources.

### ISSUE THREAD

**Issue by ferminacostajr** [TheLX5/Powerups#72]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Video**
Try adding GIFs or Videos about the problem so we can understand it better.

**External resources usage**
Try providing information about what tools do you use and what codes have you inserted in your ROM so we can understand your problem.

**Additional context**

**Comment by TheLX5** [comment]
There isn't information about what's broken. Also the template is fully intact.

Open another issue with the actual incompatibilities you've found.
